// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkSO3oUsrEa6Oc9va-1H9n6xYx6r32gJo',
    appId: '1:469765508183:web:5b5d96eef79d14bbc5a712',
    messagingSenderId: '469765508183',
    projectId: 'mural-estagio',
    authDomain: 'mural-estagio.firebaseapp.com',
    storageBucket: 'mural-estagio.appspot.com',
    measurementId: 'G-0VGSH4KK4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZAebbF88IrlEWf8GnvHqnq_6HDlHrp1E',
    appId: '1:469765508183:android:b445d23dfb725686c5a712',
    messagingSenderId: '469765508183',
    projectId: 'mural-estagio',
    storageBucket: 'mural-estagio.appspot.com',
  );
}
